### ISSUE TITLE
Server returned HTTP response code

### ISSUE THREAD

**Issue by wadhwasahil** [vishnudxb/kube-ignite#1]
Hey I am following your method, but when my logs for a pod, I get this error

```
class org.apache.ignite.spi.IgniteSpiException: Failed to retrieve Ignite pods IP addresses.

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/default/endpoints/ignite
```

**Comment by vishnudxb** [comment]
@wadhwasahil It looks like a permission error to retrieve your pods ip address. By some reason your pods cannot resolve an IP address of Kubernetes master that responses on service call. That’s the default name ‘kubernetes.default.svc.cluster.local’ and your DNS knows nothing about it. Please ensure the container the pod is running in can establish a connection with the master.

**Comment by wadhwasahil** [comment]
Yeah it was because I hadn't created a role binding. It works now. Thanks
